name: "dwoo.org"
#url: http://dwoo.org
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
urls:
  gitter: 'https://gitter.im/dwoo_project/support?utm_source=share-link&utm_medium=link&utm_campaign=share-link'
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: documentation
    values:
      header: docs
      nav: docnav
      toc: true
  - scope:
      path: plugins
    values:
      masthead: false

repository: dwoo-project/dwoo

jekyll_get:
  data: packagist
  json: 'https://packagist.org/packages/dwoo/dwoo.json'