name: "dwoo.org"
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
urls:
  gitter: 'https://gitter.im/dwoo_project/support?utm_source=share-link&utm_medium=link&utm_campaign=share-link'
documentation:
  popular:
    - {title: "Getting started", url: "1.3/getting-started.html"}
    - {title: "Dwoo for developers", url: "1.3/dwoo-for-developers.html"}
    - {title: "Dwoo for designers", url: "dwoo-for-designers.html"}
    - {title: "Template Inheritance", url: "template-inheritance.html"}
    - {title: "Shortcuts", url: "shortcuts.html"}

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed
