name: "dwoo.org"
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
navigation:
  - {title: Home, url: "/index.html"}
  - {title: Downloads, url: "/downloads.html"}
  - {title: Blog, url: "/blog.html"}
  - {title: Documentation, url: "/documentation/"}
  - {title: About, url: "/about.html"}
documentation:
  1.x:
    -
      title: "Dwoo users"
      children:
        - {title: "Getting Started", url: "getting-started.html"}
        - {title: "Using Dwoo with your framework of choice", url: "frameworks.html"}
        - {title: "Extending - How to write plugins", url: "writing-plugins.html"}
    -
      title: "Smarty user ?"
      children:
        - {title: "Using the Smarty Adapter to convert your Smarty code", url: "smarty-adapter.html"}
        - {title: "List of unsupported Smarty features", url: "smarty-support.html"}
    -
      title: "Quick Links"
      children:
        - {title: "List of $dwoo and other reserved variables", url: "dwoo-variables.html"}
        - {title: "List of iterator variables (loop, for and foreach)", url: "iterator-variables.html"}
        - {title: "Shortened syntax for power users", url: "shortcuts.html"}
    -
      title: "Designers Documentation"
      children:
        - {title: "Syntax", url: "syntax.html"}
        - {title: "Plugins", url: "plugins.html"}
    -
      title: "Stuff"
      children:
        - {title: "Dwoo Users / Sites built with it", url: "users.html"}
        - {title: "Dwoo syntax file for GeSHI", url: "files/dwoo-geshi-1.0.0.tar.gz"}
    - {title: "Changelog", url: "changelog.html"}
    - {title: "License", url: "license.html"}