# Project name
name: "dwoo.org"

# Highlighter used
highlighter: rouge

# Loaded Jekyll plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-paginate

urls:
  gitter: 'https://gitter.im/dwoo_project/support?utm_source=share-link&utm_medium=link&utm_campaign=share-link'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# Front Matter defaults
#
# The defaults key holds an array of scope/values pairs that
# define what defaults should be set for a particular file path,
# and optionally, a file type in that path.
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: documentation
    values:
      header: docs
      nav: docnav
      toc: true
  -
    scope:
      path: plugins
    values:
      masthead: false
      breadcrumb: true
  -
    scope:
      path: ""
      type: posts
    values:
      breadcrumb: true
  -
    scope:
      path: integrations/symfony
    values:
      breadcrumb: true

# Pagination
#
# The number should be the maximum number of Posts you’d like to
# be displayed per-page in the generated site.
paginate: 8
paginate_path: "/blog/page:num/"

repository: dwoo-project/dwoo

jekyll_get:
  data: packagist
  json: 'https://packagist.org/packages/dwoo/dwoo.json'