version: '3'
services:
  jekyll:
    container_name: dwoo.org_jekyll
    build:
      context: .
      dockerfile: Dockerfile-jekyll
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - LANG=C.UTF-8
      - JEKYLL_GITHUB_TOKEN=8c27ff6645069ca7ef248958312bdfcca2880514

  nginx:
    container_name: dwoo.org_nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
