FROM nginx:latest

# Expose Nginx HTTP service
EXPOSE 80

# Add the Nginx site and config
COPY nginx.conf /etc/nginx/conf.d/dwoo.conf

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Restart Nginx
RUN service nginx restart